[general]
quoteToken = "SOL"
dbConnectionStr = ""
summaryLoggingInterval = 10
dryRun = true

[txn]
skipPreflight = true
txnSubmittingRetries = 2

[pool]
requireMintDisabled = true
requireFreezeDisabled = true
requireMetadata = true
requireImage = true
requireSymbol = true
minBaseTokenInPool = 1000000
minQuoteTokenInPool = 5
maxQuoteTokenInPool = 50

[monitor]
poolCreationMonitorTimeout = 3600
poolCreationMonitorPollIntervalMs = 50
minLpBurnPercentage = 70
minPooledTokenPercentage = 40
detectRugPuller = true
lpTokenPollIntervalMs = 500
lpTokenMonitorTimeout = 300

[strategy]
takeProfitPercentage = 50
takeProfitSellPercentage = 100
stopLossPercentage = 20
stopLossSellPercentage = 100
hardCashOutTimeSec = 180
buySlippage = 0
buyFeeMicroLamports = 50000000
sellSlippage = 0
sellFeeMicroLamports = 50000000
quoteTokenBuyInPercentage = 1
minQuoteTokenIn = 0.1
maxQuoteTokenIn = 0.5
quoteTickIntervalMs = 100