[general]
quoteToken = "SOL"
dbConnectionStr = ""
summaryLoggingInterval = 10
dryRun = false
priceSampleInterval = 3
activeTasksPollingInterval = 5
sendTxnRetries = 3

[txn]
skipPreflight = true
txnSubmittingRetries = 2

[pool]
requireMintDisabled = false
requireFreezeDisabled = true
requireMetadata = true
requireImage = true
requireSymbol = true
minBaseTokenInPool = 1000000
# 2.5 - 25 initial SOL in pool suggests a 5 - 50 SOL initial liquidity.
minQuoteTokenInPool = 2.5
maxQuoteTokenInPool = 25

[monitor]
poolCreationMonitorTimeout = 3600
poolCreationMonitorPollIntervalMs = 50
minLpBurnPercentage = 70
minPooledTokenPercentage = 0
detectRugPuller = true
lpTokenPollIntervalMs = 500
lpTokenMonitorTimeout = 300

[strategy]
takeProfitPercentage = 100
takeProfitSellPercentage = 100
stopLossPercentage = 50
stopLossSellPercentage = 100
hardCashOutTimeSec = 30
buySlippage = 50
buyFeeMicroLamports = 100000000
sellSlippage = 25
sellFeeMicroLamports = 100000000
quoteTokenBuyInPercentage = 10
minQuoteTokenIn = 0.5
maxQuoteTokenIn = 1
quoteTickIntervalMs = 100

[spam]
enabled = true
spamIntervalMs = 300