[general]
quoteToken = "SOL"
dbConnectionStr = ""
summaryLoggingInterval = 10
dryRun = true
priceSampleInterval = 3
activeTasksPollingInterval = 5

[txn]
skipPreflight = true
txnSubmittingRetries = 2

[pool]
requireMintDisabled = false
requireFreezeDisabled = true
requireMetadata = true
requireImage = true
requireSymbol = true
minBaseTokenInPool = 1000000
minQuoteTokenInPool = 5
maxQuoteTokenInPool = 50

[monitor]
poolCreationMonitorTimeout = 3600
poolCreationMonitorPollIntervalMs = 50
minLpBurnPercentage = 70
minPooledTokenPercentage = 0
detectRugPuller = true
lpTokenPollIntervalMs = 500
lpTokenMonitorTimeout = 300

[strategy]
takeProfitPercentage = 100
takeProfitSellPercentage = 100
stopLossPercentage = 50
stopLossSellPercentage = 100
hardCashOutTimeSec = 30
buySlippage = 0
buyFeeMicroLamports = 50000000
sellSlippage = 0
sellFeeMicroLamports = 50000000
quoteTokenBuyInPercentage = 1
minQuoteTokenIn = 0.1
maxQuoteTokenIn = 0.5
quoteTickIntervalMs = 100