[general]
quoteToken = "SOL"
dbConnectionStr = ""
summaryLoggingInterval = 10
dryRun = false
oneShotMode = true
priceSampleInterval = 3
activeTasksPollingInterval = 5
sendTxnRetries = 0
defaultPriorityFeeLamports = 100000

[txn]
skipPreflight = true
txnSubmittingRetries = 2

[pool]
requireMintDisabled = false
requireFreezeDisabled = true
requireMetadata = true
requireImage = true
requireSymbol = true
minBaseTokenInPool = 1000000
# 2.5 - 25 initial SOL in pool suggests a 5 - 50 SOL initial liquidity.
minQuoteTokenInPool = 2
maxQuoteTokenInPool = 50

[monitor]
poolCreationMonitorTimeout = 3600
poolCreationMonitorPollIntervalMs = 50
minLpBurnPercentage = 70
minPooledTokenPercentage = 0
detectRugPuller = true
lpTokenPollIntervalMs = 500
lpTokenMonitorTimeout = 300

[strategy]
takeProfitPercentage = 100
takeProfitSellPercentage = 100
stopLossPercentage = 50
stopLossSellPercentage = 100
hardCashOutTimeSec = 15
buySlippage = 50
buyFeeMicroLamports = 50000
sellSlippage = 50
sellFeeMicroLamports = 100000
quoteTokenBuyInPercentage = 2
minQuoteTokenIn = 0.1
maxQuoteTokenIn = 0.5
quoteTickIntervalMs = 50

[spam]
enabled = true
intervalMs = 500
timeoutSec = 120
buyInAmount = 0.1
numCashOutTxns = 60